platform:ios, '9.0'
inhibit_all_warnings!
target 'myStartRating' do

pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'SSZipArchive', '~> 2.2.2'
#pod 'CCSSZipArchive', '~> 0.0.2'
pod 'JTToast', '~> 1.1.0'

end
